

CREATE DATABASE hypermarket_db;

USE hypermarket_db;

create table HYPERMARKET(
   HYPERMARKET_ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   ADDRESS VARCHAR(300) NOT NULL,
   PRIMARY KEY ( HYPERMARKET_ID )
);

create table GROCERY_ITEM(
    GROCERY_ITEM_ID INT NOT NULL AUTO_INCREMENT,
    HYPERMARKET_ID INT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    EXPIRATION_DATE DATE,
    PRIMARY KEY (GROCERY_ITEM_ID),
    FOREIGN KEY (HYPERMARKET_ID) REFERENCES HYPERMARKET(HYPERMARKET_ID)
        ON DELETE CASCADE
);

CREATE USER
  hypermarket_api_user IDENTIFIED BY 'hypermarket_user_password';

GRANT ALL ON * . * TO 'hypermarket_api_user';
FLUSH PRIVILEGES;